
import java.awt.Color;
import java.sql.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.sql.Connection;


/**
 *
 * @author okk
 */
public class Register extends javax.swing.JFrame {

    private static Connection connect=null;
    
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.setBackground(new Color(2,103,114));
        jButton1.setBackground(new Color(52,224,192));
        jButton3.setBackground(new Color(52,224,192));
        
        setTitle("UserData");
        setResizable(false);
        connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Age = new javax.swing.JSpinner();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        BirthDate = new javax.swing.JTextField();
        Country = new javax.swing.JTextField();
        Resume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(2, 103, 114));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/refer.png"))); // NOI18N
        jButton1.setText("Crear cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/edit (1).png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/live-stream.png"))); // NOI18N

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        BirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Fecha de nacimiento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Pais ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Biografia");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Email");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Edad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Country, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BirthDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(13, 13, 13)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Resume, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton1)
                        .addGap(49, 49, 49)
                        .addComponent(jButton3)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(BirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Resume, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void BirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDateActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        get_Data();
        vaciar();
        Sign_in n=new Sign_in();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        update_Data();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    
    
    public void connect(){
        try{
            
            connect=DriverManager.getConnection("jdbc:derby://localhost:1527/Streaming_Service1","user1","1234");
            //connect=DriverManager.getConnection("jdbc:derby://localhost:1527/Streaming_Service1;user=user1,password=1234");
            JOptionPane.showMessageDialog(null,"Succesfull connection!!");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"A error ocur during connection!! \n error:"+ex.getMessage());
            
        }
    }
    public void disconect(){
        try{
            if(!connect.isClosed()){
            connect.close();
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"A error ocur during connection!! \n error:"+ex);
        }
    }
    
    //this would work for the create account section but changing the null by the actual data 
    public boolean verificarVacios(){
       if((Name.getText().equals(""))){          //||(Password.getText().equals("")
          return true;
       }else{
          return false;
       }
    }
    
    public void vaciar(){
        Name.setText("");
        Email.setText("");
        Age.setValue(0);
        Password.setText("");
        BirthDate.setText("");
        Resume.setText("");
        Country.setText("");
    }
    
    
    
    public void get_Data(){
        connect();
        Statement sentency;
        int age;
        String name,email,country,password,birthdate,resume;
        if(verificarVacios()){
           JOptionPane.showMessageDialog(null,"¡Hay campos vacíos, revise!","Error",JOptionPane.ERROR_MESSAGE); 
        }else{
            try{
                name=Name.getText();  
                email=Email.getText();
                age=Integer.parseInt(Age.getValue().toString());
                password=Password.getText();
                birthdate=BirthDate.getText();
                country=Country.getText();
                resume=Resume.getText();
                connect();
                sentency=connect.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                sentency.executeUpdate("insert into register(nombre,edad,email,country,birthdate,password)"+ "values( "+"'"+name
                +"',"+age+",'"+email+"','"+country+"','"+birthdate+"','"+password+"')");
                JOptionPane.showMessageDialog(null,"Registrado");
                connect.close();
                
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Se dio el error "+ex.getMessage());
            }
        }
        
    }
    
    /*
    public void get_Data(){
        //open file 
        User us=new User();
        us.setBirthDate(BirthDate.getText());
        us.setCountry(Country.getText());
        us.setEmail(Email.getText());
        us.setResume(Resume.getText());
        us.setName(Name.getText());
        us.setPassword(Password.getText());
        try{
            DataOutputStream dataEnter= new DataOutputStream(new FileOutputStream("C:\\Users\\XPC\\OneDrive\\Imágenes\\Documentos\\Trabajos U\\Programacion cliente-servidor\\UserData.txt",true));
            dataEnter.writeUTF(us.getName());
            dataEnter.writeUTF(us.getEmail());
            dataEnter.writeUTF(us.getPassword());
            dataEnter.writeUTF(us.getCountry());
            dataEnter.writeUTF(us.getResume());
            dataEnter.writeUTF(us.getBirthDate());
            dataEnter.close();
            JOptionPane.showMessageDialog(null,"Datos almacenados");
        }catch(IOException e){
                JOptionPane.showMessageDialog(null,"Error al amacenar los datos");
                }
    }
    */
    public void erase_Data(){
        
    }
    
    
    public void update_Data(){
       
       String name,password,verify="";
       int cont=0;
       if(verificarVacios()){
           JOptionPane.showMessageDialog(null,"There is some empty spaces, please fill them in");
       }else{
            connect();
            name=Name.getText();
            password=Password.getText();
            if(buscarRepetido(6,name)==false){
                JOptionPane.showMessageDialog(null,"La cuenta con el nombre "+name+"no existe");
            }else {
                try{
                Statement sentency= connect.createStatement();
                ResultSet rs=sentency.executeQuery("select * from Register where nombre= "+"'"+ name +"'");
                while(rs.next()){
                verify=rs.getString(5);
                }
                while(!password.equals(verify) && cont<4){
                    password=JOptionPane.showInputDialog("Por favor ingrese la contrase;a de su cuenta para poder modificarla");
                    cont=cont+1;
                    if(!password.equals(verify)){
                        JOptionPane.showMessageDialog(null,"La contrase;a es incorrecta le quedan "+ cont+"intentos para volver a ingresarla");
                    }
                    if(cont>4){
                        break;
                    }
                }if(password.equals(verify)){
                    try{     
                int age;
                String email,country,birthdate,resume;    
                name=Name.getText();  
                email=Email.getText();
                age=Integer.parseInt(Age.getValue().toString());
                password=Password.getText();
                birthdate=BirthDate.getText();
                country=Country.getText();
                resume=Resume.getText();
                connect();
                sentency=connect.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                sentency.executeUpdate("insert into register(nombre,edad,email,country,birthdate,password)"+ "values( "+"'"+name
                +"',"+age+",'"+email+"','"+country+"','"+birthdate+"','"+password+"')");
                JOptionPane.showMessageDialog(null,"Registrado");
                connect.close();
                }catch(SQLException ex){
                  JOptionPane.showMessageDialog(null,"An error has ocurr "+ex.getMessage());  
                }
                }
                
                }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"An error has ocurr "+ex.getMessage());
            }
            }
       }
        
        
    }
    
     public boolean buscarRepetido(int column,String nombre){
       int cont=0;
       boolean existe=false;
       try{
          connect();
          Statement s=connect.createStatement();
          ResultSet rs=s.executeQuery("select * from Register where nombre="+"'"+nombre+"'");
          while(rs.next()){
             if(nombre.equals(rs.getString(column))){
                cont++;
             }
          }
          if(cont>0){
             existe=true;
             JOptionPane.showMessageDialog(null,"Se encontraron "+cont+"nombre iguales");
          }
       }catch(Exception ex){
          JOptionPane.showMessageDialog(null,"¡Error al buscar!"+ex.getMessage(),
                  "Error",JOptionPane.ERROR_MESSAGE);
       }
    return existe;
     }
   
   
    
    public void getUpdateU(String u){
         Name.setText(u);
     }
     public void getUpdateP(String p){
         Password.setText(p);
     }
    public void review_Data(){
        String password,name;
        try{
            connect();
            name=Name.getText();
            password=Password.getText();
            Statement sentency = connect.createStatement();
            ResultSet rs=sentency.executeQuery("select * from Register where nombre= "+"'"+ name +"'" +"AND password ="+"'"+ password+"'");
            while(rs.next()){
                Age.setValue(rs.getInt(1));
                Resume.setText(rs.getString(5));
                Country.setText(rs.getString(3));
                Email.setText(rs.getString(2));
                BirthDate.setText(rs.getString(4));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "An error had occur !! \n"
                    + "error: "+ex);
            
        };
        disconect();
    }
    
    public void llenar(String user , String password){
        Password.setText(password);
        Name.setText(user);
    }
    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Age;
    private javax.swing.JTextField BirthDate;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Resume;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
